version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: banking-backend
    ports:
      - "8000:8000"
    environment:
      # -------------------------------------------------------
      # Node 1: Intent Classification Service (chạy trên Colab)
      # Sau khi chạy notebook Intent-Service-Colab.ipynb,
      # copy URL ngrok/Pinggy vào đây:
      INTENT_SERVICE_URL: http://bsfmy-136-109-6-10.run.pinggy-free.link
      INTENT_MODEL_NAME: ngbaoan/intent-banking

      # -------------------------------------------------------
      # Node 4: Ollama LLM (chạy trên Colab)
      # Sau khi chạy notebook Ollama-Pinggy.ipynb,
      # copy URL Pinggy vào đây:
      OLLAMA_BASE_URL: http://litvn-34-125-187-71.run.pinggy-free.link
      OLLAMA_MODEL: gpt-oss:20b
    networks:
      - public_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: banking-frontend
    ports:
      - "8501:8501"
    environment:
      API_BASE_URL: http://backend:8000
    depends_on:
      - backend
    networks:
      - public_net

networks:
  public_net:
    name: banking_public_net
